### ISSUE TITLE
cache the executed html

### ISSUE THREAD

**Issue by gihnius** [unrolled/render#18]
is there an option to to allow to cache the executed html(not the parsed template) ?
because it's slow when template.execute() on a big binding(map).

**Comment by codingmusica** [comment]
You should be able to (but not currently with unrolled/render) range over Template.Templates() and Execute() each template using bytes.Buffer{} as the io.Writer.  Send, either, the Buffer or Buffer.Bytes() out to your cache depending on it's interface.

I hope I've understood and helped you.

---
This leads me to my specific need: Access to the parsed templates.

In my app, I'd like to be able to grab the parsed template contents so that I can return it within a template function.  My options now are to either not use unrolled/render, or use httptest.NewRecorder() to gather the contents using the currently exported functions.  I believe that having access to the parsed templates would offer a superior solution.

If it would help, I can make a pull request with templates exported.
Thanks!

**Comment by unrolled** [comment]
Closing, please reopen if necessary.
