### ISSUE TITLE
Custom Error Handlers on Rendering Errors

### ISSUE THREAD

**Issue by elithrar** [unrolled/render#26]
When an error is encountered as part of the rendering pipeline `http.Error` is called and displays the simple plain-text error page:

```go
func (r *Render) Render(w http.ResponseWriter, e Engine, data interface{}) {
	err := e.Render(w, data)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}
```

It would be great if there was the ability to pass your own error handler. A potential implementation would be:

* Add an `ErrorHandler http.Handler` field to the `render.Options` struct
* In `prepareOptions` call `if r.opt.ErrorHandler == nil { r.opt.ErrorHandler = defaultErrorHandler }`
* Add a `defaultErrorHandler` http.HandlerFunc that wraps `http.Error(w, http.StatusText(500), 500)`
* Package users can supply their own handler to render "pretty" error pages or otherwise handle rendering errors. (my personal use case would be to call a static 500.html page with in-lined CSS that's a little friendlier than the plain text one from net/http)

Happy to provide a PR for this but wanted to run this by you first.

**Comment by unrolled** [comment]
This would be a much welcomed change! Your implementation outline is good. I implemented something very similar for my [Secure package](https://github.com/unrolled/secure/blob/v1/secure.go#L86) as well if you want to reference that.

**Comment by elithrar** [comment]
Working on this now—failed to notice that the current call to `http.Error` uses `err.Error()` to write the rendering error to the HTTP 500 response. A couple of tests are also failing as they're expecting the error string in the response.

Three options:

1. Just write `http.StatusText(http.StatusInternalServerError)` to the response
2. Same as option 1, but also log the error before calling the handler. As there are no instances of logging errors in the package today this one was worth checking first. (this would be my preference)
3. Require users provide a function that matches `func(e error) http.Handler` - which is not particularly ideal as it requires package users to write a custom wrapper around existing error handlers to satisfy this package alone.

I'll update the tests to match the preferred implementation.

**Comment by unrolled** [comment]
I agree, option 2 would be the best approach. Thanks!

**Comment by elithrar** [comment]
With some time to finally sit down and dig through this, it won't be possible to pass a custom `http.Handler` as an option and call it from within render as it doesn't have access to the `*http.Request`:

```go
func (r *Render) Render(w http.ResponseWriter, e Engine, data interface{}) {
	err := e.Render(w, data)
	if err != nil {
		log.Printf("render: %s", err)
		// No access to *http.Request here.
		r.opt.ErrorHandler.ServeHTTP(w, r)
		return
	}
}
```

Modifying the signature of Render to accept a `*http.Request` would resolve the issue at the expense of breaking the API for any current user.

We may need to leave this unless you're happy to make the call.

**Comment by unrolled** [comment]
Oh snap... yes the lack of `http.Request` will definitely throw a wrench into that plan. 

We could look at manually rendering an error template in the [Render function](https://github.com/unrolled/render/blob/v1/engine.go#L175).  So instead of returning an error, lookup the error template name and write out a 500 status (we could add both the `htmlErrorTemplateName` and `htmlErrorStatusCode` to the options). We should still log the error... but would need to return nil to silence the the [http.Error](https://github.com/unrolled/render/blob/v1/render.go#L247) call.

What do you think, could this work?

**Comment by blachniet** [comment]
I'm a little late to the party, but have you considered returning the error from the [`Render.Render`](https://github.com/unrolled/render/blob/v1/render.go#L296) method (and methods that call that such as [`Render.HTML`](https://github.com/unrolled/render/blob/v1/render.go#L319), [`Render.Data`](https://github.com/unrolled/render/blob/v1/render.go#L305), etc? 

The caller would already have access to the `*http.Request` there in the HTTP handler where they call `Render.HTML`, and could handle the error in a custom way if they wanted to. If they didn't want to do anything custom, they could just ignore the returned error.

You could continue to call `http.Error(w, err.Error(), http.StatusInternalServerError)` upon errors in `Render.Render`, but have an option to disable that so that the user could handle the error themselves.

**Comment by elithrar** [comment]
> I'm a little late to the party, but have you considered returning the error from the Render.Render method (and methods that call that such as Render.HTML, Render.Data, etc?

That could work, but changing the signature to `func (r *Render) Render(w http.ResponseWriter, e Engine, data interface{}) error` would be API breaking. I say that knowing that the compiler won't actually complain as you can completely ignore return values.

It may be the most sensible option though.

PS: I still have plans to get to this, but it's been non-urgent with respect to other stuff!
